// ============================================================
// LIFEPILOT — REFLECTION PROMPT REPOSITORY
// 200 curated reflection prompts for the Flight Log module.
// Categories: reflection(35), curiosity(30), learning(40),
//             gratitude(30), confidence(30), relationships(35)
// ============================================================

export type ReflectionPromptCategory =
  | "reflection"
  | "curiosity"
  | "learning"
  | "gratitude"
  | "confidence"
  | "relationships";

export interface ReflectionPrompt {
  id: string;
  category: ReflectionPromptCategory;
  text: string;
  followUp?: string;
}

export const REFLECTION_PROMPTS: ReflectionPrompt[] = [
  // ── REFLECTION (35) ───────────────────────────────────────
  { id: "rfl-001", category: "reflection", text: "What made today different from yesterday?" },
  { id: "rfl-002", category: "reflection", text: "What was the best moment of your day?" },
  { id: "rfl-003", category: "reflection", text: "What was challenging today — and how did you handle it?" },
  { id: "rfl-004", category: "reflection", text: "If today had a colour, what would it be and why?" },
  { id: "rfl-005", category: "reflection", text: "What's one thing you wish you had done differently today?" },
  { id: "rfl-006", category: "reflection", text: "What surprised you today?" },
  { id: "rfl-007", category: "reflection", text: "How are you feeling right now, in three words?" },
  { id: "rfl-008", category: "reflection", text: "What's one thing that made you smile today?" },
  { id: "rfl-009", category: "reflection", text: "What's something that felt hard but you did anyway?" },
  { id: "rfl-010", category: "reflection", text: "What would you like to leave behind from today?" },
  { id: "rfl-011", category: "reflection", text: "What is one thing you are proud of from today?" },
  { id: "rfl-012", category: "reflection", text: "What does your body feel like right now?" },
  { id: "rfl-013", category: "reflection", text: "What's the one moment from today you want to remember forever?" },
  { id: "rfl-014", category: "reflection", text: "What are you still thinking about from today?" },
  { id: "rfl-015", category: "reflection", text: "If you could talk to yourself from this morning, what would you say?" },
  { id: "rfl-016", category: "reflection", text: "What's something that happened today that made you think?" },
  { id: "rfl-017", category: "reflection", text: "What energy do you want to bring into tomorrow?" },
  { id: "rfl-018", category: "reflection", text: "Describe your day as a weather report." },
  { id: "rfl-019", category: "reflection", text: "What felt unfinished today? Is it okay to let it rest?" },
  { id: "rfl-020", category: "reflection", text: "What's one thing that didn't go as planned — and what happened instead?" },
  { id: "rfl-021", category: "reflection", text: "What made today feel alive?" },
  { id: "rfl-022", category: "reflection", text: "Who or what gave you energy today?" },
  { id: "rfl-023", category: "reflection", text: "Who or what drained your energy today?" },
  { id: "rfl-024", category: "reflection", text: "What's one small thing you're grateful for from today?" },
  { id: "rfl-025", category: "reflection", text: "What would tomorrow's version of you want to tell today's version of you?" },
  { id: "rfl-026", category: "reflection", text: "What's one word that captures your whole day?" },
  { id: "rfl-027", category: "reflection", text: "What did you do today just for yourself?" },
  { id: "rfl-028", category: "reflection", text: "What are you looking forward to tomorrow?" },
  { id: "rfl-029", category: "reflection", text: "If today were a chapter in a book, what would you title it?" },
  { id: "rfl-030", category: "reflection", text: "What felt easy today that used to feel hard?" },
  { id: "rfl-031", category: "reflection", text: "What's something you noticed in yourself today?" },
  { id: "rfl-032", category: "reflection", text: "What do you need most right now?" },
  { id: "rfl-033", category: "reflection", text: "What's a small win from today you almost didn't notice?" },
  { id: "rfl-034", category: "reflection", text: "How would a kind friend describe your day?" },
  { id: "rfl-035", category: "reflection", text: "What's one thing you want to remember about today in ten years?" },

  // ── CURIOSITY (30) ────────────────────────────────────────
  { id: "cur-001", category: "curiosity", text: "What question is living in your mind right now?" },
  { id: "cur-002", category: "curiosity", text: "What's something you want to understand better?" },
  { id: "cur-003", category: "curiosity", text: "What's the most interesting thing you heard or saw today?" },
  { id: "cur-004", category: "curiosity", text: "What topic could you talk about for an hour without stopping?" },
  { id: "cur-005", category: "curiosity", text: "What's a mystery in your own life you're still figuring out?" },
  { id: "cur-006", category: "curiosity", text: "If you could learn any skill instantly, what would it be?" },
  { id: "cur-007", category: "curiosity", text: "What would you invent if you could invent anything?" },
  { id: "cur-008", category: "curiosity", text: "What's something ordinary that you find secretly fascinating?" },
  { id: "cur-009", category: "curiosity", text: "What did you look up, explore, or research today?" },
  { id: "cur-010", category: "curiosity", text: "What's something you believed before that you've changed your mind about?" },
  { id: "cur-011", category: "curiosity", text: "If you could ask one person in history one question, who and what?" },
  { id: "cur-012", category: "curiosity", text: "What part of the world do you most want to explore someday?" },
  { id: "cur-013", category: "curiosity", text: "What's a skill someone around you has that you find impressive?" },
  { id: "cur-014", category: "curiosity", text: "What's something you've always wondered but never asked?" },
  { id: "cur-015", category: "curiosity", text: "What's something new you tried recently — even something small?" },
  { id: "cur-016", category: "curiosity", text: "What would you explore if no one was watching and nothing could go wrong?" },
  { id: "cur-017", category: "curiosity", text: "What's the last thing that made you go 'Wow, I didn't know that!'?" },
  { id: "cur-018", category: "curiosity", text: "What's a question you've had since childhood that you still don't know the answer to?" },
  { id: "cur-019", category: "curiosity", text: "What subject at school feels most alive to you right now, and why?" },
  { id: "cur-020", category: "curiosity", text: "What did you notice in your surroundings today that you usually overlook?" },
  { id: "cur-021", category: "curiosity", text: "What's an idea you've been turning over in your mind?" },
  { id: "cur-022", category: "curiosity", text: "What's something you've been meaning to try but haven't yet?" },
  { id: "cur-023", category: "curiosity", text: "What's one thing you're genuinely curious about regarding yourself?" },
  { id: "cur-024", category: "curiosity", text: "What problem in the world do you wish you could help solve?" },
  { id: "cur-025", category: "curiosity", text: "What conversation did you have recently that made you think differently?" },
  { id: "cur-026", category: "curiosity", text: "What's something you could spend hours exploring online if there were no limits?" },
  { id: "cur-027", category: "curiosity", text: "What's one thing about nature that amazes you?" },
  { id: "cur-028", category: "curiosity", text: "What's a book, movie, or show that opened up new ideas for you?" },
  { id: "cur-029", category: "curiosity", text: "What's one thing about the future you are genuinely excited to see?" },
  { id: "cur-030", category: "curiosity", text: "What's something you disagree with that everyone around you seems to accept?" },

  // ── LEARNING (40) ─────────────────────────────────────────
  { id: "lrn-001", category: "learning", text: "What's one thing you learned today — from anywhere?" },
  { id: "lrn-002", category: "learning", text: "What's something you got better at this week?" },
  { id: "lrn-003", category: "learning", text: "What's one mistake you made recently that taught you something?" },
  { id: "lrn-004", category: "learning", text: "What's the most useful thing you know how to do?" },
  { id: "lrn-005", category: "learning", text: "Who taught you something important recently — even without meaning to?" },
  { id: "lrn-006", category: "learning", text: "What's something you used to find difficult that now feels easier?" },
  { id: "lrn-007", category: "learning", text: "What would you teach someone else if you could choose?" },
  { id: "lrn-008", category: "learning", text: "What's one habit or skill you're currently practising?" },
  { id: "lrn-009", category: "learning", text: "What's the difference between knowing something and understanding it?" },
  { id: "lrn-010", category: "learning", text: "What's one thing you're still learning about yourself?" },
  { id: "lrn-011", category: "learning", text: "When did you last feel the excitement of learning something completely new?" },
  { id: "lrn-012", category: "learning", text: "What's one thing you could practise for five minutes every day that would change you?" },
  { id: "lrn-013", category: "learning", text: "What's something you read, watched, or listened to that changed your thinking?" },
  { id: "lrn-014", category: "learning", text: "What's the hardest thing you've ever had to learn? How did you get through it?" },
  { id: "lrn-015", category: "learning", text: "What's one area of your life where you feel you've grown the most this year?" },
  { id: "lrn-016", category: "learning", text: "What does it feel like when you're genuinely learning something?" },
  { id: "lrn-017", category: "learning", text: "What's one thing you know now that you wish you'd known a year ago?" },
  { id: "lrn-018", category: "learning", text: "What's something you started but didn't finish — and what stopped you?" },
  { id: "lrn-019", category: "learning", text: "How do you learn best — by doing, watching, reading, or talking?" },
  { id: "lrn-020", category: "learning", text: "What's one thing you're working on getting better at?" },
  { id: "lrn-021", category: "learning", text: "What's a lesson you had to learn more than once?" },
  { id: "lrn-022", category: "learning", text: "Who in your life is someone you learn a lot from? What have they taught you?" },
  { id: "lrn-023", category: "learning", text: "What's one thing you want to be able to do in six months that you can't do now?" },
  { id: "lrn-024", category: "learning", text: "What did you try today that you'd never tried before?" },
  { id: "lrn-025", category: "learning", text: "What's the most interesting problem you've tried to solve recently?" },
  { id: "lrn-026", category: "learning", text: "When was the last time you asked for help with something difficult?" },
  { id: "lrn-027", category: "learning", text: "What skill would surprise people to know you have?" },
  { id: "lrn-028", category: "learning", text: "What's one thing you've been avoiding learning — and why?" },
  { id: "lrn-029", category: "learning", text: "What's a subject you once found boring but now find interesting?" },
  { id: "lrn-030", category: "learning", text: "What's one question you asked today?" },
  { id: "lrn-031", category: "learning", text: "What do you want to be known for knowing about?" },
  { id: "lrn-032", category: "learning", text: "What's something you could teach a younger child?" },
  { id: "lrn-033", category: "learning", text: "What's the best piece of advice you've ever received?" },
  { id: "lrn-034", category: "learning", text: "What's one thing you wish school taught you?" },
  { id: "lrn-035", category: "learning", text: "What's a new perspective that recently shifted how you see something?" },
  { id: "lrn-036", category: "learning", text: "What's something about yourself that you're still figuring out?" },
  { id: "lrn-037", category: "learning", text: "What was the last thing you practised — even for just a few minutes?" },
  { id: "lrn-038", category: "learning", text: "What's one thing you learned from a failure?" },
  { id: "lrn-039", category: "learning", text: "What's one thing you're proud you figured out on your own?" },
  { id: "lrn-040", category: "learning", text: "If you could give your younger self one piece of advice about learning, what would it be?" },

  // ── GRATITUDE (30) ────────────────────────────────────────
  { id: "gra-001", category: "gratitude", text: "What are three things — big or small — that you're grateful for today?" },
  { id: "gra-002", category: "gratitude", text: "Who helped you today, even in a tiny way?" },
  { id: "gra-003", category: "gratitude", text: "What's something about your life you usually take for granted?" },
  { id: "gra-004", category: "gratitude", text: "What made today worth waking up for?" },
  { id: "gra-005", category: "gratitude", text: "What's a simple pleasure you enjoyed today?" },
  { id: "gra-006", category: "gratitude", text: "Who is someone who makes your life better just by being in it?" },
  { id: "gra-007", category: "gratitude", text: "What's something in nature that you're grateful for?" },
  { id: "gra-008", category: "gratitude", text: "What's something your body did for you today that you're grateful for?" },
  { id: "gra-009", category: "gratitude", text: "What's a memory you're thankful to have?" },
  { id: "gra-010", category: "gratitude", text: "What's something at home that makes your life easier or more comfortable?" },
  { id: "gra-011", category: "gratitude", text: "What's a skill or ability you have that you sometimes forget to appreciate?" },
  { id: "gra-012", category: "gratitude", text: "What's something you received recently — a kind word, a favour, a gift?" },
  { id: "gra-013", category: "gratitude", text: "What's a place that makes you feel safe or happy? What do you love about it?" },
  { id: "gra-014", category: "gratitude", text: "What's something that was once difficult but now makes you grateful you went through it?" },
  { id: "gra-015", category: "gratitude", text: "Who in your family are you grateful for today, and why?" },
  { id: "gra-016", category: "gratitude", text: "What's one thing about school or learning that you're grateful for?" },
  { id: "gra-017", category: "gratitude", text: "What's a food or taste you're grateful exists in the world?" },
  { id: "gra-018", category: "gratitude", text: "What's something you can do today that you couldn't do a year ago?" },
  { id: "gra-019", category: "gratitude", text: "What's a kindness someone showed you recently that you haven't forgotten?" },
  { id: "gra-020", category: "gratitude", text: "What's something about yourself — a quality or strength — you're grateful for?" },
  { id: "gra-021", category: "gratitude", text: "What's a song, story, or piece of art that you're glad exists?" },
  { id: "gra-022", category: "gratitude", text: "What's one thing about today — even something small — that was good?" },
  { id: "gra-023", category: "gratitude", text: "What's a challenge in your life that you're secretly grateful for?" },
  { id: "gra-024", category: "gratitude", text: "What technology or invention makes your life better every day?" },
  { id: "gra-025", category: "gratitude", text: "What's a tradition or festival that fills you with warmth and gratitude?" },
  { id: "gra-026", category: "gratitude", text: "Who is a teacher or mentor — inside or outside of school — you're grateful for?" },
  { id: "gra-027", category: "gratitude", text: "What's something you have today that you once really wanted?" },
  { id: "gra-028", category: "gratitude", text: "What's one act of kindness you gave or received this week?" },
  { id: "gra-029", category: "gratitude", text: "What's something about this time in your life you'll look back on with gratitude?" },
  { id: "gra-030", category: "gratitude", text: "What's one thing you're looking forward to that you're grateful is coming?" },

  // ── CONFIDENCE (30) ───────────────────────────────────────
  { id: "cnf-001", category: "confidence", text: "What's one thing you did today that took courage?" },
  { id: "cnf-002", category: "confidence", text: "What are three things you're actually good at?" },
  { id: "cnf-003", category: "confidence", text: "When do you feel most like yourself?" },
  { id: "cnf-004", category: "confidence", text: "What's something you've done that you didn't think you could do?" },
  { id: "cnf-005", category: "confidence", text: "What's a compliment you've received that you actually believed?" },
  { id: "cnf-006", category: "confidence", text: "What would you do if you knew you couldn't fail?" },
  { id: "cnf-007", category: "confidence", text: "What's something you said or did today that you feel good about?" },
  { id: "cnf-008", category: "confidence", text: "When did you last surprise yourself with what you were capable of?" },
  { id: "cnf-009", category: "confidence", text: "What's a belief about yourself that might not be true?" },
  { id: "cnf-010", category: "confidence", text: "What does your most confident self look and feel like?" },
  { id: "cnf-011", category: "confidence", text: "What's one thing you did recently that you felt proud of — even if no one noticed?" },
  { id: "cnf-012", category: "confidence", text: "What's something you've been told you're good at that you secretly agree with?" },
  { id: "cnf-013", category: "confidence", text: "What's a fear you've faced — even partially — that made you stronger?" },
  { id: "cnf-014", category: "confidence", text: "What's something you know about yourself that others might not see?" },
  { id: "cnf-015", category: "confidence", text: "When did you last speak up for yourself or someone else?" },
  { id: "cnf-016", category: "confidence", text: "What's one thing you'd like to try that you've been too nervous to attempt?" },
  { id: "cnf-017", category: "confidence", text: "What's a challenge you're handling better than you give yourself credit for?" },
  { id: "cnf-018", category: "confidence", text: "If your best friend described you, what would they say?" },
  { id: "cnf-019", category: "confidence", text: "What's one way you showed up for yourself today?" },
  { id: "cnf-020", category: "confidence", text: "What would you say to a younger version of yourself who was afraid of something?" },
  { id: "cnf-021", category: "confidence", text: "What's one thing you can do now that used to feel impossible?" },
  { id: "cnf-022", category: "confidence", text: "What's a unique quality you have that the world needs?" },
  { id: "cnf-023", category: "confidence", text: "When was the last time you felt genuinely proud of yourself?" },
  { id: "cnf-024", category: "confidence", text: "What's something you know deeply about yourself that gives you strength?" },
  { id: "cnf-025", category: "confidence", text: "What's one thing you'd do differently if self-doubt wasn't in the room?" },
  { id: "cnf-026", category: "confidence", text: "What would you attempt if you were 10% braver?" },
  { id: "cnf-027", category: "confidence", text: "What's a difficult decision you made recently that you stand by?" },
  { id: "cnf-028", category: "confidence", text: "Who sees the best in you — and do you see it too?" },
  { id: "cnf-029", category: "confidence", text: "What's one thing that's going right in your life right now?" },
  { id: "cnf-030", category: "confidence", text: "What's one thing you'd like to say to yourself with total kindness right now?" },

  // ── RELATIONSHIPS (35) ────────────────────────────────────
  { id: "rel-001", category: "relationships", text: "Who did you spend time with today — and how did it feel?" },
  { id: "rel-002", category: "relationships", text: "Who is someone you feel completely yourself around?" },
  { id: "rel-003", category: "relationships", text: "Is there someone you've been meaning to reach out to but haven't? What's stopping you?" },
  { id: "rel-004", category: "relationships", text: "What's one thing you appreciate about a friend that you haven't told them?" },
  { id: "rel-005", category: "relationships", text: "Who challenged you recently — and how did you respond?" },
  { id: "rel-006", category: "relationships", text: "What's a quality you admire in someone you love?" },
  { id: "rel-007", category: "relationships", text: "What's one way you showed up for someone else today?" },
  { id: "rel-008", category: "relationships", text: "What does a good friendship look and feel like to you?" },
  { id: "rel-009", category: "relationships", text: "Who in your life do you want to spend more time with?" },
  { id: "rel-010", category: "relationships", text: "When did someone's words recently lift you up — or bring you down?" },
  { id: "rel-011", category: "relationships", text: "What's one thing you could do this week to strengthen a friendship?" },
  { id: "rel-012", category: "relationships", text: "What's a memory with someone you love that you want to hold onto?" },
  { id: "rel-013", category: "relationships", text: "Is there someone you've had a disagreement with? How are you feeling about it?" },
  { id: "rel-014", category: "relationships", text: "What's something kind someone did for you recently that you didn't expect?" },
  { id: "rel-015", category: "relationships", text: "What makes you a good friend?" },
  { id: "rel-016", category: "relationships", text: "Who do you go to when things feel hard? Why that person?" },
  { id: "rel-017", category: "relationships", text: "What's one thing you wish you could say to someone but haven't yet?" },
  { id: "rel-018", category: "relationships", text: "What's something you've learned from someone older than you?" },
  { id: "rel-019", category: "relationships", text: "What's something you've learned from someone younger than you?" },
  { id: "rel-020", category: "relationships", text: "Who makes you laugh until it hurts? What do you love about them?" },
  { id: "rel-021", category: "relationships", text: "What's one relationship in your life you want to take better care of?" },
  { id: "rel-022", category: "relationships", text: "What's a boundary you've held — or want to hold — in a relationship?" },
  { id: "rel-023", category: "relationships", text: "How do the people around you see you — and is that how you see yourself?" },
  { id: "rel-024", category: "relationships", text: "What's one act of kindness you can do for someone tomorrow?" },
  { id: "rel-025", category: "relationships", text: "Who in your life shows you what love looks like in action?" },
  { id: "rel-026", category: "relationships", text: "What's something a family member does that you deeply appreciate?" },
  { id: "rel-027", category: "relationships", text: "When did you last feel truly heard by someone?" },
  { id: "rel-028", category: "relationships", text: "What's a quality in others that you're drawn to — and do you have it yourself?" },
  { id: "rel-029", category: "relationships", text: "What does trust mean to you — and who do you trust most?" },
  { id: "rel-030", category: "relationships", text: "What's a relationship that has changed you in a positive way?" },
  { id: "rel-031", category: "relationships", text: "What would your closest friend say is your best quality?" },
  { id: "rel-032", category: "relationships", text: "Who have you helped recently — and how did it make you feel?" },
  { id: "rel-033", category: "relationships", text: "What's something you need from others that you sometimes forget to ask for?" },
  { id: "rel-034", category: "relationships", text: "Who in your life inspires you to be a better version of yourself?" },
  { id: "rel-035", category: "relationships", text: "What's one thing you'd like to say — with love — to someone in your life today?" },
];

export const REFLECTION_PROMPT_COUNT = REFLECTION_PROMPTS.length;
export const REFLECTION_PROMPT_CATEGORIES: ReflectionPromptCategory[] = [
  "reflection", "curiosity", "learning", "gratitude", "confidence", "relationships",
];
